SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
-- ======================================================================================
-- dba16_sys_GetAdddbfullmessage
--
--
-- Calls:		None
--
-- Description:	Add a db ful message to messages.
-- 
-- Date			Modified By			Changes
-- 11/14/2016   Aron E. Tekulsky    Initial Coding.
-- 11/22/2017   Aron E. Tekulsky    Update to Version 140.
-- ======================================================================================
--	Copyright©2001 - 2025 Aron Tekulsky.  World wide rights reserved.
--	Use of this code is free of charge but does not in any way imply transfer of 
--	Copyright ownership to the user.
-- ======================================================================================
--
BEGIN
	-- SET NOCOUNT ON added to prevent extra result sets from
	-- interfering with SELECT statements.
	SET NOCOUNT ON;

    -- Insert statements for procedure here

	EXEC sp_addmessage 
		 @msgnum=911421, -- 911DBA
		 @severity=1,    -- Informational message not generated by DB Engine       
		 @msgtext=N'Data files are %d percent full in database %s.'
END
GO
